In [22]:
print("Hello World")

Hello World


In [23]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [24]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [25]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [26]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.46012276,  0.22969806, -0.63398343,  0.57388425, -0.5589    ,
        -0.49481636,  0.13106464, -0.13793144, -0.26738065, -0.50851816]],
      dtype=float32)

In [27]:
tf.nn.softmax(predictions).numpy()

array([[0.07210045, 0.14372203, 0.06059423, 0.20276898, 0.065319  ,
        0.06964193, 0.13022292, 0.09950934, 0.08742685, 0.0686942 ]],
      dtype=float32)

In [28]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [29]:
loss_fn(y_train[:1], predictions).numpy()

2.6643887

In [30]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [31]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2924 - accuracy: 0.9160
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1406 - accuracy: 0.9590
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1057 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0880 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0729 - accuracy: 0.9770


In [32]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0636 - accuracy: 0.9791 - 402ms/epoch - 1ms/step


[0.06356082856655121, 0.9790999889373779]

In [33]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [34]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.4784248e-08, 4.9922311e-10, 1.2004939e-06, 3.1667030e-05,
        3.4497594e-12, 4.4517853e-07, 4.9044197e-14, 9.9994540e-01,
        5.0997738e-07, 2.0586802e-05],
       [6.6286301e-09, 1.7922105e-04, 9.9982029e-01, 3.5327892e-07,
        9.5014440e-18, 1.5005006e-07, 1.3267385e-08, 1.6332587e-15,
        5.5647014e-08, 2.7224433e-14],
       [5.9212624e-07, 9.9957114e-01, 1.8504652e-05, 2.2360468e-06,
        1.2441102e-05, 7.7678587e-06, 4.1580493e-06, 2.5694977e-04,
        1.2577909e-04, 3.8122920e-07],
       [9.9976999e-01, 1.4588408e-08, 7.0837195e-05, 1.2376724e-06,
        9.0144493e-07, 2.8100152e-05, 3.1066618e-05, 5.3581949e-05,
        7.5407051e-08, 4.4103777e-05],
       [5.5375290e-07, 2.4206451e-10, 2.3361688e-05, 3.3297212e-08,
        9.8833859e-01, 6.0354932e-07, 1.8124638e-07, 1.6003618e-05,
        1.3052805e-07, 1.1620534e-02]], dtype=float32)>